name: 🐛 Bug Report
description: Something isn't working correctly.
body: 
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to open source!

        Do you need some help?
        ======================

        The issue tracker is meant for bug reports only. This isn't the best place for support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before you ask a question, here are some resources to get help first:

        - Read the docs: https://react-redux.js.org/
        - Check out the troubleshooting guide: https://react-redux.js.org/troubleshooting
        - Look for/ask questions on Stack Overflow: https://stackoverflow.com/questions/tagged/redux
        - Ask in chat: https://www.reactiflux.com/

        Think you found a bug?
        ======================
        The best bug report is a failing test in the repository as a pull request. Otherwise, please use the form below.
  - type: textarea
    attributes:
      label: What version of React, ReactDOM/React Native, Redux, and React Redux are you using?
      value: |
        - React: 
        - ReactDOM/React Native: 
        - Redux:
        - React Redux:
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the current behavior?
      description: |
        If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
    validations:
      required: true
  - type: input
    attributes:
      label: Which browser and OS are affected by this issue?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Did this work in previous versions of React Redux?
      options:
      - label: "Yes"
    validations:
      required: false
