name: 👍 Feature Request
description: I'd like React Redux to do something new.
body: 
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to open source!

        Do you need some help?
        ======================

        The issue tracker is meant for bug reports only. This isn't the best place for support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before you ask a question, here are some resources to get help first:

        - Read the docs: https://react-redux.js.org/
        - Check out the troubleshooting guide: https://react-redux.js.org/troubleshooting
        - Look for/ask questions on Stack Overflow: https://stackoverflow.com/questions/tagged/redux
        - Ask in chat: https://www.reactiflux.com/
  - type: textarea
    attributes:
      label: What is the new or updated feature that you are suggesting?
      description: |
        Please provide thoughtful commentary *and code samples* on what this feature means for your product. What will it allow you to do that you can't do today? How will it make current work-arounds straightforward? What potential bugs and edge cases does it help to avoid? etc. Please keep it product-centric.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should this feature be included?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What docs changes are needed to explain this?
    validations:
      required: true
